import type { ImageSourcePropType } from "react-native"

/**
 * THE WELCOME STILL — the one place the entrance photograph is referenced.
 *
 * An app-owned frame: a player mid-pass on a floodlit pitch, the ball toward the camera, the
 * OVALBALL wordmark on the ball itself. Produced on Higgsfield with the canonical mark supplied
 * as a reference image so the lettering on the ball is reproduced faithfully rather than
 * hallucinated, reviewed by eye, and bundled.
 *
 * THE JERSEY CARRIES NO MARK. Earlier passes tried an oval badge on the player's chest
 * (embroidered, then printed) and the owner rejected both on sight as out of place -- restored
 * here to the reference composition the owner actually approved: the wordmark lives on the ball
 * only, the jersey is plain. Regenerated by giving Higgsfield the previous (badged) frame as a
 * composition reference and asking for the one change -- remove the badge, keep everything else
 * identical -- rather than a fresh prompt, which is what got the pose, lighting and ball artwork
 * this close on the first attempt.
 *
 * It carries no other words and it is never the source of anything: the mark, the motto, the
 * copy and the actions are native layers over it.
 *
 * Null draws nothing but the forest ground -- the screen still reads.
 */
export const welcomeStill: ImageSourcePropType | null = require("../../../assets/welcome/welcome-still.jpg")
