import type { MetadataRoute } from "next"

import { PRODUCT_NAME } from "@/lib/legal/metadata"

/**
 * Web app manifest, generated by Next's file convention so the
 * <link rel="manifest"> tag is emitted once and never hand-written.
 *
 * The icons here are the same Ovalball mark as the favicon and Apple touch
 * icon -- not a second logo. They live in public/icons/ rather than being
 * the app/icon.png convention file because a manifest needs stable, known
 * URLs, and the convention route's URL carries a build hash.
 *
 * The maskable icon is the same drawing with more padding. Android crops a
 * maskable icon to whatever shape the launcher uses (circle, squircle,
 * teardrop), so a mark sized for a square would lose its ends; the extra
 * margin keeps the ball inside the safe zone whatever shape is applied.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${PRODUCT_NAME} | Rugby Club Management`,
    short_name: PRODUCT_NAME,
    description:
      "Run your rugby club — fixtures, teams, training, matchdays and members in one place.",
    start_url: "/",
    display: "standalone",
    // The brand green the mark is drawn on, so the splash and launcher
    // background match the icon rather than framing it in white.
    background_color: "#014527",
    theme_color: "#014527",
    icons: [
      { src: "/icons/ovalball-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/ovalball-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/ovalball-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  }
}
