import { Directory, File, Paths } from "expo-file-system"
import * as Sharing from "expo-sharing"

/**
 * OPENING SOMETHING SOMEBODY SENT YOU.
 *
 * NO WEBVIEW, AND NO BROWSER HOP. A signed URL opened with `Linking.openURL` leaves Ovalball and lands
 * in Safari, where a private club document sits in a browser tab and in that browser's history; a
 * WebView is the same exposure with a worse PDF reader. Instead the file is fetched into the app's own
 * cache and handed to the system's document interaction sheet, which is what shows a native Quick Look
 * preview on iOS and the chooser on Android. The document never leaves the app's sandbox to be looked
 * at.
 *
 * THE SIGNED URL IS TREATED AS THE SECRET IT IS. It is short-lived and generated by the canonical
 * reader per read; nothing here stores it, logs it or puts it anywhere a person could copy it out of.
 *
 * THE CACHE COPY IS NAMED BY THE ATTACHMENT'S ID, not by its filename. Two documents legitimately
 * called `Visitor Guide.pdf` would otherwise overwrite each other, and the second person to open one
 * would read the first's.
 */

export async function openAttachment(attachment: {
  id: string
  filename: string
  mimeType: string
  signedUrl: string | null
}): Promise<{ ok: true } | { ok: false; message: string }> {
  if (!attachment.signedUrl) {
    return { ok: false, message: "This file isn't available to open just now. Try again in a moment." }
  }
  if (!(await Sharing.isAvailableAsync())) {
    return { ok: false, message: "This device can't open that file." }
  }

  try {
    const folder = new Directory(Paths.cache, "attachments", attachment.id)
    if (!folder.exists) folder.create({ intermediates: true })

    const target = new File(folder, safeName(attachment.filename, attachment.mimeType))
    // Re-fetched rather than reused: the previous copy may be a revision behind, and a document that
    // has been replaced must not be the one somebody reads.
    if (target.exists) target.delete()
    await File.downloadFileAsync(attachment.signedUrl, target, { idempotent: true })

    await Sharing.shareAsync(target.uri, {
      mimeType: attachment.mimeType,
      UTI: utiFor(attachment.mimeType),
      dialogTitle: attachment.filename,
    })
    return { ok: true }
  } catch {
    // The URL is deliberately absent from this message and from any log: it is a bearer credential
    // for a private file.
    return { ok: false, message: "Couldn't open that file. Try again." }
  }
}

/**
 * A filename that cannot escape the folder it is written into.
 *
 * `original_filename` is whatever the sender's device called it, which means it is untrusted text on
 * the way back out. A name carrying `../` would write outside the cache folder; a name with no
 * extension gives the system nothing to preview with.
 */
function safeName(filename: string, mimeType: string): string {
  const cleaned = filename.replace(/[/\\]+/g, "_").replace(/^\.+/, "").trim()
  if (!cleaned) return `attachment${extensionFor(mimeType)}`
  return /\.[A-Za-z0-9]{1,8}$/.test(cleaned) ? cleaned : `${cleaned}${extensionFor(mimeType)}`
}

function extensionFor(mimeType: string): string {
  if (mimeType === "application/pdf") return ".pdf"
  if (mimeType === "image/png") return ".png"
  if (mimeType === "image/webp") return ".webp"
  if (mimeType === "image/jpeg") return ".jpg"
  return ""
}

/** iOS previews by uniform type identifier; without one it falls back to a generic file. */
function utiFor(mimeType: string): string | undefined {
  if (mimeType === "application/pdf") return "com.adobe.pdf"
  if (mimeType === "image/jpeg") return "public.jpeg"
  if (mimeType === "image/png") return "public.png"
  if (mimeType === "image/webp") return "org.webmproject.webp"
  return undefined
}
